FROM aliyun-hn1-tcr-prod-registry.cn-shenzhen.cr.aliyuncs.com/ux168/base/openjdk8:20230901

COPY csa-ld-proxy-service-boot/target/jar/*.jar /app/app.jar



EXPOSE 9021

ENTRYPOINT ["java","-XX:+UseContainerSupport", "-XX:InitialRAMPercentage=50.0", "-XX:MaxRAMPercentage=50.0","-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/tmp/csa-ld-proxy-service.hprof","-XX:+UseG1GC","-jar","app.jar"]