<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- 设置一个父级依赖 -->
    <parent>
        <groupId>com.ux168</groupId>
        <artifactId>ux168-parent-common</artifactId>
        <version>2023.3.7.2-RELEASE</version>
    </parent>
    <groupId>com.ux168</groupId>
    <artifactId>csa-ld-proxy-service</artifactId>
    <!-- 以聚合pom的方式打包 -->
    <packaging>pom</packaging>
    <!-- 版本号 -->
    <version>2025.0.1</version>

    <!-- 定义变量 -->
    <properties>
        <ux168.csa.common.version>2023.0.1</ux168.csa.common.version>
        <postgresql.version>42.7.4</postgresql.version>
    </properties>

    <!-- 聚合模块 -->
    <modules>
        <module>csa-ld-proxy-service-api</module>
        <module>csa-ld-proxy-service-biz</module>
        <module>csa-ld-proxy-service-boot</module>
    </modules>

    <!-- 依赖管理，定义公共版本 -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.ux168</groupId>
                <artifactId>csa-ld-proxy-service-api</artifactId>
                <version>${project.version}${version.suffix}</version>
            </dependency>
            <dependency>
                <groupId>com.ux168</groupId>
                <artifactId>csa-ld-proxy-service-biz</artifactId>
                <version>${project.version}${version.suffix}</version>
            </dependency>
            <dependency>
                <groupId>com.ux168</groupId>
                <artifactId>csa-ld-proxy-service-boot</artifactId>
                <version>${project.version}${version.suffix}</version>
            </dependency>
            <!-- CSA自定义jar包 -->
            <dependency>
                <artifactId>ux168-csa-common</artifactId>
                <groupId>com.ux168</groupId>
                <version>${ux168.csa.common.version}${version.suffix}</version>
            </dependency>

            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>${postgresql.version}</version>
            </dependency>
        </dependencies>

    </dependencyManagement>


    <build>
        <!-- 最终生成的文件名字，所有子模块继承这个配置 -->
        <finalName>${project.artifactId}-${project.version}${version.suffix}</finalName>
        <plugins>
            <!--生成源文件插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
            </plugin>

            <!-- 单元测试执行插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>

            <!-- 安装插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>install</phase>
                        <configuration>
                            <groupId>com.ux168</groupId>
                            <artifactId>${project.artifactId}</artifactId>
                            <version>${project.version}${version.suffix}</version>
                            <packaging>pom</packaging>
                            <file>pom.xml</file>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- 部署插件 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <id>deploy-file</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy-file</goal>
                        </goals>
                        <configuration>
                            <!--对应maven配置文件setting.xml中的server标签中的id，即不同环境对应不同的
                            账号密码
                            开发阶段上传到snapshot仓库，上线阶段上传到release仓库 -->
                            <repositoryId>${version.repository.id}</repositoryId>
                            <url>${version.repository.url}</url>
                            <groupId>com.ux168</groupId>
                            <artifactId>${project.artifactId}</artifactId>
                            <version>${project.version}${version.suffix}</version>
                            <packaging>pom</packaging>
                            <file>pom.xml</file>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>