<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>csa-ld-proxy-service</artifactId>
        <groupId>com.ux168</groupId>
        <version>2025.0.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>csa-ld-proxy-service-boot</artifactId>
    <packaging>jar</packaging>
    <properties>
        <!-- 不上传此jar包 -->
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.ux168</groupId>
            <artifactId>csa-ld-proxy-service-biz</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>install</phase>
                        <configuration>
                            <groupId>com.ux168</groupId>
                            <artifactId>${project.artifactId}</artifactId>
                            <version>${project.version}${version.suffix}</version>
                            <packaging>jar</packaging>
                            <file>target/${project.artifactId}-${project.version}${version.suffix}.jar</file>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>com.ux168.csa.service.boot.Application</mainClass>
                    <outputDirectory>./target/jar</outputDirectory>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>